[package]
name = "tldr-github" # the name of the package
version = "0.0.1"    # the current version, obeying semver
authors = ["Felipe Sere <felipe@sere.dev>"]
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0"
async-std = "1.2.0"
chrono = { version = "0.4.10", features = ["serde"] }
diesel = { version = "1.4.3", features = ["sqlite", "r2d2", "chrono"] }
diesel_migrations = { version = "1.4.0", features = ["sqlite"] }
futures = "0.3.1"
log = "0.4"
percent-encoding = "2.1.0"
r2d2 = "0.8.7"
rusqlite = "0.20.0"
serde = { version = "1.0.0", features = ["derive"] }
serde_json = "1.0.0"
simplelog = "0.7.4"
tide = "0.4.0"
url = "2.1.0"
surf = "1.0.3"
