-- Your SQL goes here
CREATE TABLE repos (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ,
  title TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
